export const company = {
  name: "TNJ",
  tagline: "Catálogo de Produtos",
  whatsapp: "5582999999999",
  email: "contato@tnj.com.br",
  whatsappMessage: "Olá! Gostaria de solicitar um orçamento pelo catálogo TNJ.",
};

export const products = [
  {
    id: "tnj-001",
    name: "Kit Empresarial Premium",
    category: "Kits",
    code: "TNJ-001",
    price: 289.9,
    featured: true,
    badge: "Destaque",
    description: "Conjunto completo para apresentação corporativa com acabamento premium.",
    image: "assets/produtos/kit-premium.jpg",
  },
  {
    id: "tnj-002",
    name: "Linha Essencial",
    category: "Linha Básica",
    code: "TNJ-002",
    price: 89.9,
    featured: false,
    description: "Opção econômica com excelente custo-benefício para revenda.",
    image: "assets/produtos/linha-essencial.jpg",
  },
  {
    id: "tnj-003",
    name: "Pacote Atacado 12un",
    category: "Atacado",
    code: "TNJ-003",
    price: 749.0,
    featured: true,
    badge: "Atacado",
    description: "Pacote com 12 unidades para pedidos em volume.",
    image: "assets/produtos/pacote-atacado.jpg",
  },
  {
    id: "tnj-004",
    name: "Edição Limitada",
    category: "Especiais",
    code: "TNJ-004",
    price: 349.9,
    featured: true,
    badge: "Novo",
    description: "Lançamento exclusivo com quantidade limitada.",
    image: "assets/produtos/edicao-limitada.jpg",
  },
  {
    id: "tnj-005",
    name: "Acessório Complementar",
    category: "Acessórios",
    code: "TNJ-005",
    price: 45.5,
    featured: false,
    description: "Item complementar ideal para compor pedidos maiores.",
    image: "assets/produtos/acessorio.jpg",
  },
  {
    id: "tnj-006",
    name: "Combo Promocional",
    category: "Promoções",
    code: "TNJ-006",
    price: 199.9,
    featured: false,
    badge: "Promo",
    description: "Combinação promocional com desconto especial por tempo limitado.",
    image: "assets/produtos/combo-promo.jpg",
  },
];
