export const company = {
  name: "TNJ 3D",
  tagline: "Premium & Prototipagem",
  whatsapp: "5582999999999",
  email: "contato@tnj3d.com.br",
  whatsappMessage: "Olá! Gostaria de solicitar um orçamento pelo catálogo TNJ 3D.",
};

export const products = [
  {
    id: "tnj3d-001",
    name: "Prototipagem Rápida",
    category: "Prototipagem",
    code: "TNJ3D-001",
    price: 89.9,
    featured: true,
    badge: "Destaque",
    description: "Impressão 3D de protótipos funcionais com acabamento premium e alta precisão.",
    image: "assets/produtos/prototipagem.jpg",
  },
  {
    id: "tnj3d-002",
    name: "Miniatura Personalizada",
    category: "Miniaturas",
    code: "TNJ3D-002",
    price: 149.9,
    featured: true,
    badge: "Popular",
    description: "Miniaturas sob medida para colecionadores, eventos e presentes exclusivos.",
    image: "assets/produtos/miniatura.jpg",
  },
  {
    id: "tnj3d-003",
    name: "Peça Técnica Industrial",
    category: "Peças Técnicas",
    code: "TNJ3D-003",
    price: 219.0,
    featured: true,
    badge: "Industrial",
    description: "Peças de reposição, engrenagens e componentes com tolerância ajustada.",
    image: "assets/produtos/peca-tecnica.jpg",
  },
  {
    id: "tnj3d-004",
    name: "Escultura Decorativa 3D",
    category: "Decoração",
    code: "TNJ3D-004",
    price: 179.9,
    featured: false,
    description: "Objetos decorativos com acabamento artístico e cores personalizadas.",
    image: "assets/produtos/escultura.jpg",
  },
  {
    id: "tnj3d-005",
    name: "Kit Atacado 10 Peças",
    category: "Atacado",
    code: "TNJ3D-005",
    price: 649.0,
    featured: false,
    badge: "Atacado",
    description: "Pacote com 10 impressões do mesmo modelo — ideal para revenda e eventos.",
    image: "assets/produtos/atacado.jpg",
  },
  {
    id: "tnj3d-006",
    name: "Modelo Arquitetônico",
    category: "Arquitetura",
    code: "TNJ3D-006",
    price: 399.9,
    featured: false,
    badge: "Novo",
    description: "Maquetes e modelos arquitetônicos em escala com detalhamento preciso.",
    image: "assets/produtos/arquitetura.jpg",
  },
];
